### ISSUE TITLE
Error with query involving math and nested query

### ISSUE THREAD

**Issue by byronwall** [pootzko/InfluxData.Net#45]
I am receiving an error when trying to run a query that executes correctly from Grafana and the Influx CLI.  The specific query is: 

```SELECT c * ((a + 16.7) / (b + 14.7)) as corrected FROM (SELECT MEAN("PT-1601") as a, MEAN("PT-2502") as b, MEAN("FT-2501") as c FROM "all_data" WHERE time > 1493328796387ms and time < 1493342639051ms GROUP BY time(1s) fill(linear))```

This is being executed against a measurement "all_data" that has the fields required "PT-1601", etc.

When using the InfluxData API I am receiving the following error:

```
"System.AggregateException: One or more errors occurred. ---> InfluxData.Net.Common.Infrastructure.InfluxDataApiException: InfluxData API responded with status code=BadRequest, response={""error"":""error parsing query: found 16.7, expected ) at line 1, char 18""}

   at InfluxData.Net.Common.RequestClients.RequestClientBase.HandleIfErrorResponse(HttpStatusCode statusCode, String responseBody)
   at InfluxData.Net.Common.RequestClients.RequestClientBase.<RequestAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.RequestClients.InfluxDbRequestClient.<QueryAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.RequestClients.InfluxDbRequestClient.<GetQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.ClientModules.ClientModuleBase.<ResolveSingleGetSeriesResultAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.ClientModules.BasicClientModule.<QueryAsync>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at InfluxExcelAddin.InfluxDbInterface.GetQueryResult(String query)
   at InfluxExcelAddin.InfluxDbExcelFunctions.GetQueryResult_R(Object query)
---> (Inner Exception #0) InfluxData.Net.Common.Infrastructure.InfluxDataApiException: InfluxData API responded with status code=BadRequest, response={""error"":""error parsing query: found 16.7, expected ) at line 1, char 18""}

   at InfluxData.Net.Common.RequestClients.RequestClientBase.HandleIfErrorResponse(HttpStatusCode statusCode, String responseBody)
   at InfluxData.Net.Common.RequestClients.RequestClientBase.<RequestAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.RequestClients.InfluxDbRequestClient.<QueryAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.RequestClients.InfluxDbRequestClient.<GetQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.ClientModules.ClientModuleBase.<ResolveSingleGetSeriesResultAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.ClientModules.BasicClientModule.<QueryAsync>d__4.MoveNext()<---
"
```

When I have a little time later, I can try and replicate the issue with a minimal database.  Until then, if there's an obvious reason this query won't work, please let me know.

**Comment by byronwall** [comment]
For what it's worth, it looks like sub queries were added in Influx 1.2 which is what I am running.

**Comment by pootzko** [comment]
Hi, yes, that is correct. I believe this is the same issue as #43 and #44.

**Comment by pootzko** [comment]
Hi, sorry for the delay. I believe the fix I implemented based on #44 should fix it for you as well. 

If you're still using this, could you please let me know? :)
If you're not using it any more, please let me know as well. :D 

Thanks!

**Comment by byronwall** [comment]
I'll update and take a look when I get a minute.  Thanks for letting me know it should be resolved.

**Comment by byronwall** [comment]
Using the new version, the above query now runs correctly.  Thanks for addressing that issue.

As an aside, I got burned by the flipped parameters on `QueryAsync`.  In hindsight I see the comment in the Release Notes on Nuget but I guess I only checked the release notes on GitHub.  Regardless, it's working now...  thanks again.

**Comment by pootzko** [comment]
Cool, glad it helped. If you can, could you please let me know which query started failing for QueryAsync? You were probably escaping something that now doesn't need to be escaped any more?

thnx

**Comment by byronwall** [comment]
The original query (up above) is the only one that was failing.  After updating the library, I had trouble with the flipped parameters for `query` and `database` on `QueryAsync`.  I got thrown off because I didn't realize they changed but the code still compiled since they're both strings.  Once I flipped those parameters around everywhere I used `QueryAsync`, everything works as expected.
