### ISSUE TITLE
Use form data to submit query

### ISSUE THREAD

**Issue by vgt** [pootzko/InfluxData.Net#53]
Hi all,
I recently ran into an issue with long queries (requesting a lot of fields) where the URI that is being constructed gets too long and due to the "q=" parameter that has more than 64000 characters the request is rejected ("URI too long").

Though I admit that maybe that type of query is questionable, I found out that InfluxDB also reads the query parameter from multipart form data (see https://github.com/influxdata/influxdb/commit/f58a50c231afd6ee775ce213461c7c0043cd724f)

With the following code I was able to successfully submit a longer query to InfluxDB:

```
HttpClient client = new HttpClient();
MultipartFormDataContent form = new MultipartFormDataContent();
form.Add(new StringContent("..."), "u");
form.Add(new StringContent("..."), "p");
form.Add(new StringContent(reallyLargeQuery), "q");
string url = $"http://localhost:8086/query?db={this.database}";

client.PostAsync(url, form)
```
Would that be something that could be changed in this client?

**Comment by vgt** [comment]
Something like this maybe?

https://github.com/vgt/InfluxData.Net/commit/63fce60a77f51523a08b5eb1812d4f9dc7d30028

**Comment by pootzko** [comment]
Seems good. I'll test it and if it doesn't break other requests, implement and deploy it. Thanks!

**Comment by dreamon-dd** [comment]
+1 for the implementation, got the same issue with Uri string too long.

**Comment by pootzko** [comment]
I just tested this and integration tests for older versions of influx fail with this approach. I'll start working on v1.3 support and implement this there.

**Comment by mahendrent** [comment]
I'll add my +1 here too... ran into this issue when trying to create a long continuous query.

**Comment by pootzko** [comment]
Hi all,

this is now implemented on the dev branch. Would any of you be willing to give it a test perhaps? Download the source, build a dll, include it in your project (which obviously uses one of these long queries) and let me know if it works fine for you?

I added @vgt's suggestion to the codebase and all the integration tests I have are passing, so I'd say it didn't break anything, but I'd like to know if it works for you in the real environment.

Thanks!

**Comment by dreamon-dd** [comment]
Perfect! I'll give it a try and let you know.

**Comment by dreamon-dd** [comment]
So, tested a little today. Got the issue, that instead of:
`InfluxDbRequestClient.QueryAsync(string query, HttpMethod method, string dbName = null, string epochFormat = null, long? chunkSize = null)`
which is virtual, the call goes to overriden:
`InfluxDbRequestClient_v_1_0_0.QueryAsync(string query, HttpMethod method, string dbName = null, string epochFormat = null, long? chunkSize = null)`
which has older implementation with passing query to uri directly and therefore throwing same exception: Uri too long.
Tried specifying both InfluxDbVersion.Latest and InfluxDbVersion.v_1_3.

**Comment by pootzko** [comment]
Ungh! Sounds like a bug :D

Ok, will fix and push the changes in the evening when I get back home and let you know when I push the changes. Sorry for that.

**Comment by pootzko** [comment]
Fixed, should be alright now.

**Comment by pootzko** [comment]
All tests are passing so I'll consider this implemented, and I'll deploy it now as part of nuget v8. If you find any bugs with it, please reopen the case. And thanks everyone for help!

**Comment by dreamon-dd** [comment]
Bad news. Tried now v8 and already old queries don't work anymore (were working on v7).
Query is very simple:
  select first(*) from rp1s.Data where time >= '2017-08-03T11:28:56.7270000Z' and time <= '2017-08-03T11:58:56.7270000Z'
Exception:
  Cannot send a content-body with this verb-type.
Stack trace:
```
   at System.Net.HttpWebRequest.CheckProtocol(Boolean onRequestStream)
   at System.Net.HttpWebRequest.BeginGetRequestStream(AsyncCallback callback, Object state)
   at System.Net.Http.HttpClientHandler.StartGettingRequestStream(RequestState state)
   at System.Net.Http.HttpClientHandler.PrepareAndStartContentUpload(RequestState state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.Common.RequestClients.RequestClientBase.<RequestInnerAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.Common.RequestClients.RequestClientBase.<RequestAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.RequestClients.InfluxDbRequestClient.<QueryFormDataAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.RequestClients.InfluxDbRequestClient.<QueryAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.RequestClients.InfluxDbRequestClient.<GetQueryAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.ClientModules.ClientModuleBase.<ResolveSingleGetSeriesResultAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.ClientModules.BasicClientModule.<QueryAsync>d__1.MoveNext()
```
Stack trace is not very informative without line numbers (because I was running on nuget package), but maybe you can see where the problem can be. Otherwise I can also make test with compiled dev. version.

**Comment by pootzko** [comment]
Ok, thanks for reporting this, I'll look into it. 

In the meantime, there is a flag on the `InfluxDbClientConfiguration` - `QueryLocation` which will allow you to use the old approach.

If you have the time, it would be helpful if you could take a look into it as well. I imagine it's probably something silly, but we'll see. 

Thanks

**Comment by pootzko** [comment]
Question - are you using .net core or 461?

**Comment by pootzko** [comment]
I think I know what the problem is. Your call is using the the GetQueryAs which usest the GET http verb which does not support formdata. I'll try to fix this tomorrow.

**Comment by dreamon-dd** [comment]
4.6.1

**Comment by pootzko** [comment]
Deployed v8.0.1, all should be fine now. I tested both net461 and netcore2.0 and all tests now pass for both targets. Let me know. :) 

cheers

**Comment by dreamon-dd** [comment]
Tested, works super, thanks a lot!
