### ISSUE TITLE
Select query somtimes returns "BadRequest"

### ISSUE THREAD

**Issue by dragonn2** [pootzko/InfluxData.Net#69]
Hi,

I am trying to select some data from InfluxDB and somtimes it fails.
The query can select some value before specific timestamp:
SELECT \"Int\" FROM \"db\" WHERE \"TagName\"='MachineStatusMessage.1' AND \"time\" < '2017-12-15T05:08:51Z' ORDER BY time DESC LIMIT 1

The data is there but the result is:

> Exception Type: InfluxData.Net.Common.Infrastructure.InfluxDataApiException
Error message: InfluxData API responded with status code=BadRequest, response=query interrupted
Stack trace: 
   at InfluxData.Net.InfluxDb.Helpers.ResponseExtensions.Validate(QueryResponse queryResponse, Boolean throwOnWarning)
   at InfluxData.Net.InfluxDb.ClientModules.ClientModuleBase.ResolveSingleGetSeriesResultChunked(IInfluxDataApiResponse response)
   at InfluxData.Net.InfluxDb.ClientModules.ClientModuleBase.<ResolveSingleGetSeriesResultAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InfluxData.Net.InfluxDb.ClientModules.BasicClientModule.<QueryAsync>d__1.MoveNext()``

Any ideas what is happening here?

**Comment by Zero3** [comment]
> InfluxData API responded with status code=BadRequest

Sounds like a HTTP `400 Bad Request` response was returned by the server (database). Which means that this issue likely has nothing to do with InfluxData.Net if it works sometimes and sometimes not :).
